### ISSUE TITLE
app works ONLY one time

### ISSUE THREAD

**Issue by Unixware** [arma7x/K-Pocket-Browser#1]
sorry mate, app looks fine but that worked ONLY ONE F time, then everytime I open this it just displays a blue/purple screen then ... nothing ! I bet is demo ... or something similar (so we must get the ad-ware from the store?) thanx

**Comment by arma7x** [comment]
Your device ?

**Comment by Unixware** [comment]
Nokia 800 tough  (2.5.2) thx

**Comment by arma7x** [comment]
Yout install it from KaiStore or here https://github.com/arma7x/K-Pocket-Browser/blob/master/application.zip ?

**Comment by Unixware** [comment]
This works! thanks

**Comment by arma7x** [comment]
remove this lines https://github.com/arma7x/K-Pocket-Browser/blob/master/app.js#L2014-L2044 to disable ads
